import { useMemo, useState } from "react";
import type { DataScope, PortalUser } from "../api/API";
import { useOrganizations, usePermissions, useRoles, useSaveUser, useUsers } from "../hooks/usePortal";
import { useTenants } from "../hooks/useTenants";
import { Modal } from "./Organizations";

const PageIntro = ({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) => <div className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-600">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{description}</p></div>;
const Metric = ({ label, value }: { label: string; value: number }) => <div className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight text-blue-700">{value}</p></div>;
const actions = ["view", "create", "edit", "delete", "export", "approve"];

export function PermissionManagement() {
  const { data: permissions = [], isLoading } = usePermissions(); const { data: roles = [] } = useRoles();
  const modules = useMemo(() => Object.entries(permissions.reduce<Record<string, typeof permissions>>((groups, permission) => { (groups[permission.module] ??= []).push(permission); return groups; }, {})), [permissions]);
  return <main className="mx-auto max-w-[1400px] px-6 py-10"><PageIntro eyebrow="Identity & access" title="Permission Management" description="Platform-defined action permissions are the only permissions available to custom roles. This makes approval, export, and destructive actions independently controllable." />
    <section className="grid gap-4 sm:grid-cols-3"><Metric label="Permission rules" value={permissions.length} /><Metric label="Role templates" value={roles.length} /><Metric label="Platform modules" value={modules.length} /></section>
    <section className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><h2 className="text-lg font-semibold text-slate-900">Module / action matrix</h2><p className="mt-1 text-sm text-slate-500">The catalog is platform-managed; custom roles only select from it.</p></div>{isLoading ? <p className="p-10 text-center text-sm text-slate-500">Loading permissions…</p> : <table className="w-full min-w-[840px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-3">Module</th>{actions.map((action) => <th key={action} className="px-4 py-3 text-center">{action}</th>)}<th className="px-6 py-3">Roles using module</th></tr></thead><tbody>{modules.map(([module, items]) => { const keys = new Set(items.map((item) => item.key)); const usage = roles.filter((role) => role.permissionKeys.some((key) => keys.has(key))).length; return <tr key={module} className="border-t border-slate-100"><td className="px-6 py-4 font-semibold capitalize text-slate-800">{module}</td>{actions.map((action) => <td key={action} className="px-4 py-4 text-center">{items.some((item) => item.action === action) ? <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-emerald-50 text-xs font-bold text-emerald-700">✓</span> : <span className="text-slate-300">—</span>}</td>)}<td className="px-6 py-4 text-slate-600">{usage} role{usage === 1 ? "" : "s"}</td></tr>; })}</tbody></table>}</section>
  </main>;
}

const scopeFor = (user: PortalUser): DataScope => user.dataScope ?? { mode: user.organizationIds.length || user.tenantIds.length ? "Selected" : "None", organizationIds: user.organizationIds, tenantIds: user.tenantIds, regions: [], teams: [] };
const scopeLabel = (scope: DataScope) => scope.mode === "All" ? "All data" : scope.mode === "None" ? "No access" : "Selected data";

export function DataPermissions() {
  const { data: users = [] } = useUsers(); const { data: organizations = [] } = useOrganizations(); const { data: tenants = [] } = useTenants(); const save = useSaveUser();
  const [editing, setEditing] = useState<PortalUser | null>(null); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [bulkMode, setBulkMode] = useState<DataScope["mode"]>("None");
  const applyBulk = () => selectedIds.forEach((id) => { const user = users.find((item) => item.id === id); if (user) { const current = scopeFor(user); save.mutate({ ...user, dataScope: { ...current, mode: bulkMode, organizationIds: bulkMode === "Selected" ? current.organizationIds : [], tenantIds: bulkMode === "Selected" ? current.tenantIds : [] } }); } });
  return <main className="mx-auto max-w-[1400px] px-6 py-10"><PageIntro eyebrow="Identity & access" title="Data Permissions" description="Set effective data access explicitly. No access is the safe default; selected scopes can include ownership, expiry, and a grant reason." />
    <section className="grid gap-4 sm:grid-cols-4"><Metric label="Organizations" value={organizations.length} /><Metric label="Tenants" value={tenants.length} /><Metric label="Selected scopes" value={users.filter((user) => scopeFor(user).mode === "Selected").length} /><Metric label="No data access" value={users.filter((user) => scopeFor(user).mode === "None").length} /></section>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 px-6 py-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Effective user access</h2><p className="mt-1 text-sm text-slate-500">Data scope is separate from a role’s action permissions.</p></div><div className="flex items-center gap-2"><select aria-label="Bulk access mode" value={bulkMode} onChange={(event) => setBulkMode(event.target.value as DataScope["mode"])} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option>None</option><option>Selected</option><option>All</option></select><button type="button" disabled={!selectedIds.length || save.isPending} onClick={applyBulk} className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-700 disabled:cursor-not-allowed disabled:opacity-50">Apply to {selectedIds.length || "selected"}</button></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3"><input aria-label="Select all users" type="checkbox" checked={users.length > 0 && selectedIds.length === users.length} onChange={() => setSelectedIds(selectedIds.length === users.length ? [] : users.map((user) => user.id))} /></th><th className="px-6 py-3">User</th><th className="px-6 py-3">Access mode</th><th className="px-6 py-3">Scope detail</th><th className="px-6 py-3">Expiry / owner</th><th className="px-6 py-3">Action</th></tr></thead><tbody>{users.map((user) => { const scope = scopeFor(user); return <tr key={user.id} className="border-t border-slate-100"><td className="px-4 py-4"><input aria-label={`Select ${user.name}`} type="checkbox" checked={selectedIds.includes(user.id)} onChange={() => setSelectedIds((ids) => ids.includes(user.id) ? ids.filter((id) => id !== user.id) : [...ids, user.id])} /></td><td className="px-6 py-4"><p className="font-semibold text-slate-800">{user.name}</p><p className="mt-1 text-xs text-slate-500">{user.email}</p></td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${scope.mode === "All" ? "bg-amber-50 text-amber-700" : scope.mode === "None" ? "bg-slate-100 text-slate-600" : "bg-blue-50 text-blue-700"}`}>{scopeLabel(scope)}</span></td><td className="px-6 py-4 text-slate-600">{scope.mode === "Selected" ? `${scope.organizationIds.length} org · ${scope.tenantIds.length} tenant` : "—"}</td><td className="px-6 py-4 text-slate-600">{scope.expiresAt ?? "No expiry"}<span className="block text-xs text-slate-400">{scope.owner ?? "No owner"}</span></td><td className="px-6 py-4"><button type="button" onClick={() => setEditing({ ...user, dataScope: scope })} className="rounded-lg border border-slate-200 px-3 py-2 font-semibold text-blue-700 hover:bg-blue-50">Manage scope</button></td></tr>; })}</tbody></table></div>
    </section>{editing && <ScopeModal user={editing} organizations={organizations} tenants={tenants} saving={save.isPending} onClose={() => setEditing(null)} onSave={(user) => save.mutate(user, { onSuccess: () => setEditing(null) })} />}</main>;
}

function ScopeModal({ user, organizations, tenants, saving, onClose, onSave }: { user: PortalUser; organizations: { id: string; name: string }[]; tenants: { id: string; name: string }[]; saving: boolean; onClose: () => void; onSave: (user: PortalUser) => void }) {
  const [scope, setScope] = useState<DataScope>(scopeFor(user)); const toggle = (key: "organizationIds" | "tenantIds", id: string) => setScope((current) => ({ ...current, [key]: current[key].includes(id) ? current[key].filter((item) => item !== id) : [...current[key], id] }));
  return <Modal title={`Manage scope · ${user.name}`} onClose={onClose}><div className="space-y-5"><fieldset><legend className="text-sm font-semibold text-slate-800">Access mode</legend><div className="mt-2 grid gap-2 sm:grid-cols-3">{(["None", "Selected", "All"] as const).map((mode) => <label key={mode} className={`flex cursor-pointer items-center gap-2 rounded-xl border p-3 text-sm ${scope.mode === mode ? "border-blue-300 bg-blue-50" : "border-slate-200"}`}><input type="radio" checked={scope.mode === mode} onChange={() => setScope({ ...scope, mode })} />{mode === "None" ? "No access" : mode === "Selected" ? "Selected data" : "All data"}</label>)}</div></fieldset>{scope.mode === "Selected" && <><ScopeChecks label="Organizations" selected={scope.organizationIds} items={organizations} onToggle={(id) => toggle("organizationIds", id)} /><ScopeChecks label="Tenants" selected={scope.tenantIds} items={tenants} onToggle={(id) => toggle("tenantIds", id)} /></>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Scope owner<input value={scope.owner ?? ""} onChange={(event) => setScope({ ...scope, owner: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 p-3" placeholder="Access owner" /></label><label className="text-sm font-medium text-slate-700">Expiry date<input type="date" value={scope.expiresAt ?? ""} onChange={(event) => setScope({ ...scope, expiresAt: event.target.value || undefined })} className="mt-1 w-full rounded-lg border border-slate-200 p-3" /></label></div><label className="block text-sm font-medium text-slate-700">Grant reason<textarea value={scope.reason ?? ""} onChange={(event) => setScope({ ...scope, reason: event.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-slate-200 p-3" placeholder="Why is this access required?" /></label><div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2">Cancel</button><button type="button" disabled={saving} onClick={() => onSave({ ...user, dataScope: scope, organizationIds: scope.mode === "Selected" ? scope.organizationIds : [], tenantIds: scope.mode === "Selected" ? scope.tenantIds : [] })} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Save scope</button></div></div></Modal>;
}
const ScopeChecks = ({ label, selected, items, onToggle }: { label: string; selected: string[]; items: { id: string; name: string }[]; onToggle: (id: string) => void }) => <fieldset><legend className="text-sm font-semibold text-slate-800">{label}</legend><div className="mt-2 grid max-h-36 gap-2 overflow-y-auto sm:grid-cols-2">{items.map((item) => <label key={item.id} className="flex items-center gap-2 rounded-lg border border-slate-100 p-2 text-sm"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => onToggle(item.id)} />{item.name}</label>)}</div></fieldset>;
