import { type FormEvent, useState } from "react";
import type { SubscriptionPlan, TenantFeature } from "../api/API";
import { useFeatures, useSaveFeature, useSavePlan, useSubscriptionPlans } from "../hooks/usePortal";
import { useTenants } from "../hooks/useTenants";
import { Badge, Field, Modal, PageTitle } from "./Organizations";

export const Subscriptions = () => {
  const { data: plans = [] } = useSubscriptionPlans();
  const { data: features = [] } = useFeatures();
  const { data: tenants = [] } = useTenants();
  const save = useSavePlan();
  const [editing, setEditing] = useState<Partial<SubscriptionPlan> | null>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (editing) save.mutate(editing, { onSuccess: () => setEditing(null) }); };
  return <main className="page-shell mx-auto max-w-[1400px] px-6 py-10"><PageTitle title="Subscription & License" description="Manage plan catalog, tenant seat limits, renewal status, and usage" action="+ Add Plan" onAction={() => setEditing({ name: "", priceLabel: "", seatLimit: 10, active: true, featureIds: [] })} />
    <section className="mt-8 grid gap-5 md:grid-cols-3">{plans.map((plan) => <article key={plan.id} className="rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-semibold">{plan.name}</h2><Badge value={plan.active ? "Active" : "Inactive"} /></div><p className="mt-3 text-2xl font-bold text-blue-600">{plan.priceLabel}</p><p className="mt-3 text-sm text-slate-600">{plan.seatLimit} seats included</p><p className="mt-1 text-sm text-slate-600">{tenants.filter((tenant) => tenant.plan === plan.name).length} tenants on this plan</p><button type="button" onClick={() => setEditing(plan)} className="mt-5 rounded-lg border px-3 py-2 text-blue-600">Edit plan</button></article>)}</section>
    <section className="mt-8 rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Tenant license usage</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3">Tenant</th><th className="p-3">Plan</th><th className="p-3">Seats</th><th className="p-3">Renewal</th><th className="p-3">License</th></tr></thead><tbody>{tenants.map((tenant) => <tr key={tenant.id} className="border-b border-slate-100"><td className="p-3 font-medium">{tenant.name}</td><td className="p-3">{tenant.plan}</td><td className="p-3">{tenant.users} / {tenant.seatLimit ?? plans.find((plan) => plan.name === tenant.plan)?.seatLimit ?? 0}</td><td className="p-3">{tenant.renewalDate ?? "Not set"}</td><td className="p-3"><Badge value={tenant.licenseStatus ?? "Active"} /></td></tr>)}</tbody></table></div></section>
    {editing && <Modal title={editing.id ? "Edit Plan" : "Create Plan"} onClose={() => setEditing(null)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Plan name" value={editing.name ?? ""} onChange={(value) => setEditing({ ...editing, name: value })} /><Field label="Price label" value={editing.priceLabel ?? ""} onChange={(value) => setEditing({ ...editing, priceLabel: value })} /><Field label="Seat limit" type="number" value={String(editing.seatLimit ?? 0)} onChange={(value) => setEditing({ ...editing, seatLimit: Number(value) })} /><label className="text-sm font-medium">Availability<select value={String(editing.active ?? true)} onChange={(event) => setEditing({ ...editing, active: event.target.value === "true" })} className="mt-1 w-full rounded-lg border p-3"><option value="true">Active</option><option value="false">Inactive</option></select></label><fieldset className="sm:col-span-2"><legend className="text-sm font-semibold text-slate-700">Included features</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{features.map((feature) => <label key={feature.id} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" checked={(editing.featureIds ?? []).includes(feature.id)} onChange={() => setEditing({ ...editing, featureIds: (editing.featureIds ?? []).includes(feature.id) ? (editing.featureIds ?? []).filter((id) => id !== feature.id) : [...(editing.featureIds ?? []), feature.id] })} />{feature.name}</label>)}</div></fieldset><div className="sm:col-span-2 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={() => setEditing(null)} className="rounded-lg border px-4 py-2">Cancel</button><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Save Plan</button></div></form></Modal>}
  </main>;
};

export const Features = () => {
  const { data: features = [] } = useFeatures();
  const { data: plans = [] } = useSubscriptionPlans();
  const save = useSaveFeature();
  const [editing, setEditing] = useState<Partial<TenantFeature> | null>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (editing) save.mutate(editing, { onSuccess: () => setEditing(null) }); };
  return <main className="page-shell mx-auto max-w-[1400px] px-6 py-10"><PageTitle title="Feature Management" description="Create platform capabilities and set plan eligibility; tenant overrides are managed in Tenant Details" action="+ Add Feature" onAction={() => setEditing({ name: "", key: "", description: "", eligiblePlans: ["Basic"], active: true })} />
    <section className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{features.map((feature) => <article key={feature.id} className="rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-lg font-semibold">{feature.name}</h2><Badge value={feature.active ? "Active" : "Inactive"} /></div><p className="mt-2 text-sm text-slate-500">{feature.description}</p><p className="mt-4 text-sm text-slate-600">Eligible plans: {feature.eligiblePlans.join(", ")}</p><button type="button" onClick={() => setEditing(feature)} className="mt-5 rounded-lg border px-3 py-2 text-blue-600">Edit feature</button></article>)}</section>
    {editing && <Modal title={editing.id ? "Edit Feature" : "Create Feature"} onClose={() => setEditing(null)}><form onSubmit={submit} className="space-y-4"><Field label="Feature name" value={editing.name ?? ""} onChange={(value) => setEditing({ ...editing, name: value })} /><Field label="Feature key" value={editing.key ?? ""} onChange={(value) => setEditing({ ...editing, key: value })} /><Field label="Description" value={editing.description ?? ""} onChange={(value) => setEditing({ ...editing, description: value })} /><fieldset><legend className="text-sm font-semibold">Eligible plans</legend><div className="mt-2 flex flex-wrap gap-3">{plans.map((plan) => <label key={plan.id} className="flex items-center gap-2"><input type="checkbox" checked={(editing.eligiblePlans ?? []).includes(plan.name)} onChange={() => setEditing({ ...editing, eligiblePlans: (editing.eligiblePlans ?? []).includes(plan.name) ? (editing.eligiblePlans ?? []).filter((item) => item !== plan.name) : [...(editing.eligiblePlans ?? []), plan.name] })} />{plan.name}</label>)}</div></fieldset><div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={() => setEditing(null)} className="rounded-lg border px-4 py-2">Cancel</button><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Save Feature</button></div></form></Modal>}
  </main>;
};
