import { type FormEvent, useState } from "react";
import type { Role } from "../api/API";
import { useDeleteRole, usePermissions, useRoles, useSaveRole, useUsers } from "../hooks/usePortal";
import { Modal, PageTitle } from "./Organizations";
import { ConfirmDialog } from "../ui/Feedback";

const Roles = () => {
  const { data: roles = [] } = useRoles();
  const { data: permissions = [] } = usePermissions();
  const { data: users = [] } = useUsers();
  const save = useSaveRole();
  const remove = useDeleteRole();
  const [editing, setEditing] = useState<Partial<Role> | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Role | null>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (editing) save.mutate(editing, { onSuccess: () => setEditing(null) }); };
  const togglePermission = (key: string) => setEditing((current) => current ? { ...current, permissionKeys: (current.permissionKeys ?? []).includes(key) ? (current.permissionKeys ?? []).filter((item) => item !== key) : [...(current.permissionKeys ?? []), key] } : current);
  return <main className="page-shell mx-auto max-w-[1400px] px-6 py-10"><PageTitle title="Role & Permission Management" description="System roles are protected; create custom roles with granular action permissions" action="+ Create Custom Role" onAction={() => setEditing({ name: "", description: "", permissionKeys: [] })} />
    <section className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{roles.map((role) => { const usage = users.filter((user) => user.roleIds.includes(role.id)).length; return <article key={role.id} className="rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{role.name}</h2><p className="mt-1 text-sm text-slate-500">{role.description}</p></div>{role.isSystem && <span className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">System</span>}</div><div className="mt-5 flex gap-4 text-sm text-slate-600"><span>{role.permissionKeys.length} permissions</span><span>{usage} assigned user{usage === 1 ? "" : "s"}</span></div><div className="mt-5 flex gap-2">{role.isSystem ? <span className="text-sm text-slate-400">Protected system role</span> : <><button type="button" onClick={() => setEditing(role)} className="rounded-lg border px-3 py-2 text-blue-600">Edit</button><button type="button" onClick={() => setDeleteTarget(role)} className="rounded-lg border border-red-200 px-3 py-2 text-red-600">Delete</button></>}</div></article>; })}</section>
    <section className="mt-8 rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Permission catalog</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{permissions.map((permission) => <div key={permission.key} className="rounded-xl bg-slate-50 p-3"><p className="font-medium text-slate-800">{permission.module}</p><p className="text-sm text-slate-500">{permission.description}</p></div>)}</div></section>
    {editing && <Modal title={editing.id ? "Edit Custom Role" : "Create Custom Role"} onClose={() => setEditing(null)}><form onSubmit={submit}><label className="block text-sm font-medium">Role name<input required value={editing.name ?? ""} onChange={(event) => setEditing({ ...editing, name: event.target.value })} className="mt-1 w-full rounded-lg border p-3" /></label><label className="mt-4 block text-sm font-medium">Description<input required value={editing.description ?? ""} onChange={(event) => setEditing({ ...editing, description: event.target.value })} className="mt-1 w-full rounded-lg border p-3" /></label><fieldset className="mt-5"><legend className="text-sm font-semibold">Permissions</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{permissions.map((permission) => <label key={permission.key} className="flex items-center gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" checked={(editing.permissionKeys ?? []).includes(permission.key)} onChange={() => togglePermission(permission.key)} />{permission.description}</label>)}</div></fieldset><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setEditing(null)} className="rounded-lg border px-4 py-2">Cancel</button><button disabled={save.isPending} className="rounded-lg bg-blue-600 px-4 py-2 text-white">Save Role</button></div></form></Modal>}
    {deleteTarget && <ConfirmDialog title={`Delete ${deleteTarget.name}?`} description={users.some((user) => user.roleIds.includes(deleteTarget.id)) ? "This role is still assigned to users and cannot be deleted. Reassign those users first." : "This permanently removes the custom role from the sample workspace."} confirmLabel="Delete role" confirmDisabled={users.some((user) => user.roleIds.includes(deleteTarget.id))} onClose={() => setDeleteTarget(null)} onConfirm={() => remove.mutate(deleteTarget.id, { onSuccess: () => setDeleteTarget(null) })} />}
  </main>;
};
export default Roles;
